##
# This code was generated by
# \ / _    _  _|   _  _
#  | (_)\/(_)(_|\/| |(/_  v1.0.0
#       /       /       

module Twilio
  module REST
    class Preview < Domain
      ##
      # Initialize the Preview Domain
      def initialize(twilio)
        super
        
        @base_url = 'https://preview.twilio.com'
        @host = 'preview.twilio.com'
        @port = 443
        
        # Versions
        @sync = nil
        @wireless = nil
        @insights = nil
      end
      
      ##
      # Version sync of preview
      def sync
        @sync ||= Sync.new self
      end
      
      ##
      # Version wireless of preview
      def wireless
        @wireless ||= Wireless.new self
      end
      
      ##
      # Version insights of preview
      def insights
        @insights ||= Insights.new self
      end
      
      def services
        self.sync.services
      end
      
      def commands
        self.wireless.commands
      end
      
      def devices
        self.wireless.devices
      end
      
      def rate_plans
        self.wireless.rate_plans
      end
      
      def calls
        self.insights.calls
      end
      
      ##
      # Provide a user friendly representation
      def to_s
        '#<Twilio::REST::Preview>'
      end
    end
  end
end